config/routes.rb
Musictrivia::Application.routes.draw do

  root 'game#index'

  post 'game/play' => 'game#play'
  post 'game/answer' => 'game#answer'
  post 'game/start' => 'game#start'
  post 'game/by_year_start' => 'game#by_year_start'
  post 'game/by_year_answer' => 'game#by_year_answer'

  get 'api/song/random' => 'api/song#random'
  get 'api/question/new(/:year)' => 'api/question#new'

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :songs
	has_one :artist
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_and_belongs_to_many :songs
	has_and_belongs_to_many :albums

	scope :named, -> (name) { where("lower(name) = ?", name.downcase) }
end

app/models/chart_top100_year.rb
class ChartTop100Year < ActiveRecord::Base
	has_one :song, foreign_key: "id", primary_key: "song_id"
	has_many :songs, foreign_key: "id", primary_key: "song_id"

	scope :year_range, -> (min, max) {where('year >= ? AND year <= ?', min, max)}
	scope :year, -> (year) { where(year: year) }
	scope :available_songs, -> { joins(:songs).where('chart_top100_years.song_id = songs.id') }
end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :album
	belongs_to :artist

  scope :named, -> (name) { where("lower(name) = ?", name.downcase) }
  scope :like, -> (name) { where("lower(name) LIKE \"%#{name}%\"") }

	def create_clip
		self.create_uuid

		temp_path = "#{Rails.root}/tmp/clip.aiff"
    save_path = "#{Rails.root}/public/audio/#{self.clip}.mp3"
    read_path = MUSIC_SEARCH_DIR + self.filename

    if File.exists? save_path
      return save_path
    end

    if File.exists? read_path
      puts "Converting #{read_path}"
      cmd = "ffmpeg -y -i \"#{read_path}\" -ss 00:00:30 -t 20 \"#{temp_path}\""
      convert = `#{cmd}`
    end

    if File.exists? temp_path
      puts "Clipping and saving to #{save_path}"
      cmd = "ffmpeg -i \"#{temp_path}\" -f mp3 -acodec libmp3lame -ab 128000 -ar 44100 -af afade=t=out:st=18:d=2,afade=t=in:st=0:d=2 \"#{save_path}\""
      clip = `#{cmd}`

      File.delete temp_path
    end

    if (File.exists?(save_path) && File.size(save_path) > 1000)
    	return save_path
    end

    return false
	end

	def create_uuid
		if self.clip.nil?
			self.clip = SecureRandom.uuid
			self.save
		end

		return self.clip
	end

  def url
    "#{PUBLIC_AUDIO_DIR}/#{self.clip}.mp3"
  end
end

app/models/trivia_question.rb
class TriviaQuestion < ActiveRecord::Base
	belongs_to :trivia_question_type
	belongs_to :album
	belongs_to :artist
	belongs_to :song

	def self.create_with_song(song, type)
		return self.create(
			song: song,
			artist: song.artist,
			uuid: SecureRandom.uuid,
			trivia_question_type: type
		)
	end

	def try_answer(answer)
		case self.trivia_question_type.answer_model
		when "Artist"
			self.is_correct = self.artist.name.downcase === answer.downcase ? true : false
		end

		self.save

		return self.is_correct
	end
end

app/models/trivia_question_type.rb
class TriviaQuestionType < ActiveRecord::Base
	scope :model, -> (model) { where(answer_model: model) }
	scope :property, -> (property) { where(answer_property: property) }
end

app/controllers/api/question_controller.rb
class Api::QuestionController < ActionController::Base
  
  # Generates a question with given criteria
	def new
    question = nil
    song = nil

    question_type = TriviaQuestionType.model("Artist").property("name").first
    
    # Default is random
    if (params[:year] && (1960..2013).include?(params[:year].to_i))
      chart_results = ChartTop100Year.year(params[:year].to_i).available_songs
      if chart_results.length > 0
        song = chart_results.sample.song
      end
    else
      song = Song.first(:offset => rand(Song.count))
    end
    
    clip = song.create_clip
    output_question(question_type, song)
  end

  private

  def output_question(question_type, song)
    if question_type && song
      question = TriviaQuestion.new()
      question.uuid = SecureRandom.uuid
      question.trivia_question_type = question_type
      question.album = song.album
      question.artist = song.artist
      question.song = song
    end

    if question && song
     question.save

     render json: {
       success: true,
       question: {
         id: question.uuid,
         text: question_type.text
       },
       audio: {
         url: "http://#{request.host_with_port}#{song.url}"
       }
     }
    else
      render json: {
        success: false
      }
    end
  end


end

app/controllers/api/song_controller.rb
class Api::SongController < ActionController::Base
  
	# Find a random song and save it to the public directory
	# Output: json object with path to song clip
  def random
  	song = Song.first(:offset => rand(Song.count))
  	clip = song.create_clip

  	if clip
  		render json: {
  			success: true,
  			audio: {
          url: "http://#{request.host_with_port}#{song.url}"
        }
  		}.to_json
  	else
  		render json: {
  			sucess: false
  		}.to_json
  	end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
  end

  def play
  	@message = ""

  	type = params[:type]

  	case type
  	when "by_year"
  		@message = ""
  	end

  end

  def choose

  end

  def by_year_start
    @year_chosen = params[:year]
    @current_song = get_random_song_by_range(@year_chosen.to_i)
    @current_song.create_clip

    @current_question = TriviaQuestion.create_with_song(
      @current_song,
      TriviaQuestionType.find_by_text('name the artist')
    )
  end

  def by_year_answer
    answer = params[:answer]
    question = TriviaQuestion.find_by_uuid(params[:question])

    @correct_answer = question.try_answer(answer)
    by_year_start
  end

  private

  def get_random_song_by_range(year_chosen)
    songs_from_charts = ChartTop100Year.year_range(year_chosen-1, year_chosen+1).available_songs
    random = Random.rand(songs_from_charts.length)
    return songs_from_charts[random].song
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/game/_answer.html.erb
<%= form_tag(game_by_year_answer_path, method: :post, remote: true) do %>
	<%= text_field_tag("answer") %>
	<%= hidden_field_tag("question", @current_question.uuid) %>
	<%= hidden_field_tag("year", @year_chosen) %>
	<%= submit_tag("Answer") %>
<% end %>

app/views/game/_by_year.html.erb
<div class="by_year">
	Fine, pick a year...
</div>

app/views/game/_by_year_song.html.erb
<p>Playing song... Guess the artist!</p>

app/views/game/_by_year_start.html.erb
<%= form_tag(game_by_year_start_path, method: :post, remote: true) do %>
	<%= text_field_tag("year") %>
	<%= submit_tag("go") %>
<% end %>

app/views/game/_start.html.erb
<div class="start">
	<h2>How do you want to play</h2>
	<ul>
		<li>
			<%= link_to "Enter a year, I'll give you Billboard Top 100 singles from around that time", game_play_path(type: 'by_year'), remote: true, method: :post, class: "btn btn-primary" %>
		<li>Completely random, and quite challenging</li>
	</ul>
</div>

app/views/game/by_year_answer.js.erb
$('.message').html("Correct? " + "<%= @correct_answer.to_s %>");
$('.game-content').html("<%= escape_javascript(render 'by_year_song') %>");
$('.answer').html("<%= escape_javascript(render 'answer') %>");

Game.state.year_chosen = <%= @year_chosen %>;
Game.state.current_song = '<%= @current_song.url %>';
Game.state.current_question = '<%= @current_question.uuid %>';
Game.state.played_songs.push('<%= @current_song.clip %>');

Game.start();

app/views/game/index.html.erb
<div class="user"></div>
<div class="message">Welcome to Guess Who</div>
<div class="game-content">
	<%= render 'start' %>
</div>
<div class="answer"></div>

app/views/game/play.js.erb
$('.message').html("<%= @message %>");
$('.game-content').html("<%= escape_javascript(render 'by_year') %>");
$('.answer').html("<%= escape_javascript(render 'by_year_start') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>say who?</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>